### ISSUE TITLE
The plugin doesn't highlight non-printable characters

### ISSUE THREAD

**Issue by victormoliveira1** [redoPop/SublimeGremlins#12]
## Description of the Issue

Sublime Gremlins doesn't highlight [Next Line](https://unicode-explorer.com/c/0085) (Codepoint U+0085, NEL), [Arabic Letter Mark](https://unicode-explorer.com/c/061C) (Codepoint U+061C, ALM), [Ogham Space Mark](https://unicode-explorer.com/c/1680) (Codepoint U+1680, OSPM) and [Mongolian Vowel Separator](https://unicode-explorer.com/c/180E) (Codepoint U+180E, MVS) when inserted on a text file.

My observation was based from this [table of non-printing characters](https://npp-user-manual.org/docs/views/#show-symbol) where I confirmed that only NEL, ALM, OSPM and MVS wasn't detected by Sublime Gremlins plugin.

## Debug Information

Windows 10 22H2 (Build 19045.2965)
Sublime Text 4 Build 4143
Plugins: Package Control v3.4.1, Sublime Gremlins v1.1.2

**Comment by redoPop** [comment]
Thanks for reporting this, and for taking the time to make it so clear and detailed.

Could I ask you to double check that `U+0085` (Next Line) isn't highlighted on your system?

I was able to verify the other three missing codepoints and opened #13 to add them, but `U+0085` _should_ be covered by current code. I see it highlighted on my system, but I'm running macOS and don't have direct access to a Windows machine. (Our other details, including ST build number, are identical.)

**Comment by victormoliveira1** [comment]
Hi @redoPop! Sorry for the late reply.

You're right, the `U+0085` (Next Line) is indeed highlighted on my system with Sublime Gremlins v1.1.2, I just checked it. I think I just got lost in my tests when I posted it.

**Comment by victormoliveira1** [comment]
> Thanks for reporting this, and for taking the time to make it so clear and detailed.
> 
> Could I ask you to double check that `U+0085` (Next Line) isn't highlighted on your system?
> 
> I was able to verify the other three missing codepoints and opened #13 to add them, but `U+0085` _should_ be covered by current code. I see it highlighted on my system, but I'm running macOS and don't have direct access to a Windows machine. (Our other details, including ST build number, are identical.)

Hi @redoPop, any news regarding this issue/PR? Thank you.

**Comment by redoPop** [comment]
Thanks for the nudge! The character list has now been updated in Sublime Gremlins v1.1.3.
