### ISSUE TITLE
Broken gutter icon.

### ISSUE THREAD

**Issue by sowizz** [redoPop/SublimeGremlins#2]
Hi,

I'm using material UI theme and syntax-higlighting, and gutter icon shows as broken, see:

![image](https://cloud.githubusercontent.com/assets/1541634/16485400/d5a7e0ee-3ebe-11e6-818f-1e7bf4a23eda.png)

Is there anything I can do about it?

**Comment by sowizz** [comment]
If someone encounters this issue, there is something wrong with the path to the icon. Changing it into: `GUTTER_ICON = 'Packages/Gremlins/icons/white.png'` resolves the problem.

**Comment by keith-hall** [comment]
It is even broken with the Default theme. I changed the line here (https://github.com/redoPop/SublimeGremlins/blob/531f7e51191942c8937cbe2fe59afc52f306ff66/Gremlins.py#L37) to:

    GUTTER_ICON = os.path.join('Packages', PACKAGE_DIR, 'icons', 'white.png').replace('\\', '/')

and that fixed it for me. ST wants Unix style path separators, but `os.path.join` gives Windows path separators on Windows, for obvious reasons.

**Comment by redoPop** [comment]
Huge apologies for the long delay in addressing this: I'd misconfigured my GitHub notifications and missed this issue entirely. D'oh!

Version 0.0.6 is now on Package Control, and incorporates 441827d which should fix this issue for all users. Thanks for debugging this, @sowizz and @keith-hall!
